server:
  port: 8761

eureka:
  instance:
    hostname: itry-discovery-server
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    registerWithEureka: false
    fetchRegistry: false