eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

rest:
  url:
    route-service: itry-route-service

management.endpoints.web.exposure.include: hystrix.stream