server:
  port: 8888

spring:
  application:
    name: itry-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/itry-discovery-server, classpath:config/itry-calculate-travel-service, classpath:config/itry-route-service, classpath:config/itry-service-gateway