server.port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management.endpoints.web.exposure.include: '*'

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    itry-route-service: /route/**
    itry-calculate-travel-service: /calculate-travel/**